name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.0'

    - name: Install dependencies
      run: |
        gem install bundler -v 2.6.8  # Cài đặt bundler nếu chưa có
        bundle install  # Cài đặt các dependencies từ Gemfile

    - name: Build Jekyll site
      run: |
        bundle exec jekyll build  # Xây dựng trang web với Jekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site  # Chỉ định thư mục _site để deploy lên GitHub Pages
